<a href="https://colab.research.google.com/github/IbrahemAmar/ML-Exercises-PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resourse notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


Intorduction to Tensors

Creating tensors

In [ ]:
##Creating Tensors

tensor_A = torch.tensor([1,3,4])
print(tensor_A , tensor_A.size())

tensor_B = torch.tensor([[14,76,3],[3,4,5]])
print(tensor_B , tensor_B.size() , tensor_B.dtype)

tensor_C = torch.tensor([[[14,76,3],[3,4,5]]])
print(tensor_C , tensor_C.size() , tensor_C.dtype)

tensor([1, 3, 4]) torch.Size([3])
tensor([[14, 76,  3],
        [ 3,  4,  5]]) torch.Size([2, 3]) torch.int64
tensor([[[14, 76,  3],
         [ 3,  4,  5]]]) torch.Size([1, 2, 3]) torch.int64


#Random Tensors

In [ ]:
##Random Tensors

random_tensor_A = torch.rand(size=(1,2))
print(random_tensor_A , random_tensor_A.dtype)

random_tensor_B = torch.rand(1,2,3)
print(random_tensor_B , random_tensor_B.dtype)

random_image = torch.rand(244,244,3)
print(random_image.dtype , random_image.size())

tensor([[0.5359, 0.0221]]) torch.float32
tensor([[[0.7391, 0.6689, 0.5414],
         [0.0826, 0.5240, 0.1401]]]) torch.float32
torch.float32 torch.Size([244, 244, 3])


#Zeros and Ones tensors


In [ ]:
#Zeros and Ones tensors

tensor_Zeros = torch.zeros(size=(1,2))
print(tensor_Zeros)

tensor_Ones = torch.ones(1,6)
print(tensor_Ones)

tensor([[0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.]])


#Create range of tensor


In [ ]:
#Create range of tensor

zero_to_eighteen = torch.arange(start=0, end=18, step=1)
print(zero_to_eighteen)

eighteen_ones = torch.ones_like(input= zero_to_eighteen)
print(eighteen_ones)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


#Tensors datatype and get inforamtion


In [ ]:
#Tensors datatype and get inforamtion

float_16_tensor = torch.tensor([4,2,1] ,
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed (torch.float16 = torch.half , torch.float32 = torch.float, torch.float64 = torch.double)
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded


# Create a tensor
some_tensor = torch.rand(3, 4)


# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7798, 0.9428, 0.2833, 0.9596],
        [0.8793, 0.8712, 0.3395, 0.9979],
        [0.1219, 0.2925, 0.0741, 0.0528]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


#Manipulating tensors / tensor operations


In [ ]:
#Manipulating tensors / tensor operations

# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
print("Plus: " ,tensor + 10)

# Subtract a number 10
print("Substract: " ,tensor - 10)

# Multiply it by 10
print("multiply: " ,tensor * 10)

# Can also use torch functions
torch.multiply(tensor, 10)
print("multiply built in: " ,torch.multiply(tensor, 10))

#for assign we can use "tensor = tensor + 10 .."


Plus:  tensor([11, 12, 13])
Substract:  tensor([-9, -8, -7])
multiply:  tensor([10, 20, 30])
multiply built in:  tensor([10, 20, 30])


#Matrix multiplication

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work


2. The resulting matrix has the shape of the outer dimensions:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)


Note: "@" in Python is the symbol for matrix multiplication.


In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape


torch.Size([3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
print(tensor_A.shape)

tensor_B = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(tensor_B.size())

torch.matmul(tensor_A, tensor_B) # (this will error)

torch.Size([3, 2])
torch.Size([2, 3])


tensor([[ 9., 12., 15.],
        [19., 26., 33.],
        [29., 40., 51.]])

#Finding the min, max, mean, sum

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Index where max value occurs: 9
Index where min value occurs: 0


#Change tensor datatype


In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(0, 10, 1)
tensor.dtype

torch.int64

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

#Reshaping, stacking, squeezing and unsqueezing


In [79]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [80]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [82]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [83]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [84]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [85]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [86]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [87]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


#Indexing (selecting data from tensors)

In [88]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [89]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [90]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [91]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [92]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [93]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

#PyTorch tensors & NumPy


In [94]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [95]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [98]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [99]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility (trying to take the random out of random)

In [107]:
import torch
import random

# # Set the random seed
RANDOM_SEED=36 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.4978, 0.4356, 0.0132, 0.5109],
        [0.7582, 0.1383, 0.6524, 0.9391],
        [0.6839, 0.3550, 0.9829, 0.9012]])

Tensor D:
tensor([[0.4978, 0.4356, 0.0132, 0.5109],
        [0.7582, 0.1383, 0.6524, 0.9391],
        [0.6839, 0.3550, 0.9829, 0.9012]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

#Running tensors on GPUs (and making faster computations)

In [1]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [2]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

 Putting tensors (and models) on the GPU

In [3]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [5]:
# copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu , tensor_back_on_cpu.device

(array([1, 2, 3]), 'cpu')